import { ClerkProvider } from '@clerk/nextjs'
import '../globals.css'
import type { Metadata } from 'next'
import style from './page.module.css'
import Topbar from '@/components/shared/Topbar'
import LeftSiderbar from '@/components/shared/LeftSiderbar'
import RightSiderbar from '@/components/shared/RightSiderbar'
import Bottombar from '@/components/shared/Bottombar'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'impossible',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang='en'>
<body className={`${inter.className}`} style={{margin:'0',overflow:'hidden'}}>
  <Topbar/>
  <main style={{overflow:'hidden'}}>
<div className={style.contain}>
<LeftSiderbar/>
<div style={{height:'101vh'}}>
{children}
</div>

<RightSiderbar/>
</div>

  </main>
{/* <Bottombar/> */}
</body>
    </html>
</ClerkProvider>
  )
}
